import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Link, NavLink, Navigate, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom';
import { Activity, ArrowLeft, BarChart3, CalendarDays, Check, ChevronDown, ChevronRight, CircleAlert, Clock3, Dumbbell, Flame, LayoutDashboard, MoreHorizontal, Plus, Search, Sparkles, TrendingUp, UserRound, Users, X } from 'lucide-react';
import { apiUrl } from './lib/appBase';
import { useInterfaceTranslation, useLanguage } from './lib/i18n';

type Delivery = { id:number; plan_id:number; client_id:number; channel:string; available_at:string; status:string; sent_at?:string; viewed_at?:string; confirmed_at?:string; feedback?:string };
type Client = { id:number; name:string; email:string; initials:string; goal:string; age:number; weight:number; height:number; fitness_level:string; condition:string; limitations:string; equipment:string; preferences:string; days_per_week:number; status:string; last_active:string; sessions?:Record<string,number>; plan?:{id:number;status:string;week_label:string}|null; delivery?:Delivery|null };
type Exercise = { name:string; sets:number; reps:string; intensity:string; rest:string; duration?:string; instructions:string };
type Workout = { id:string; day:string; title:string; focus:string; duration:number; exercises:Exercise[] };
type Plan = { id:number; week_label:string; status:string; rationale:string; workouts:Workout[] };
type Session = { id:number; title:string; scheduled_date:string; status:string; duration:number|null; difficulty:number|null; notes:string; performance:{exercise:string;sets:string;load:string}[] };
type Progress = { id:number; recorded_date:string; weight:number; waist:number; body_fat:number; squat_max:number; feedback:string };
type ClientDetail = { client:Client; plan:Plan|null; delivery:Delivery|null; sessions:Session[]; progress:Progress[]; analysis:{completion:number;avgDifficulty:number;suggestion:string} };
type CalendarSession = { id:number; client_id:number; client_name:string; client_initials:string; title:string; scheduled_date:string; start_time:string; training_type:string; status:'upcoming'|'completed'|'cancelled'|'missed'; duration:number; notes:string; recurrence_rule:string };

const statusLabel: Record<string,string> = { on_track:'On track', attention:'Needs attention', needs_plan:'Plan needed', missed:'Missed sessions' };
const deliveryLabel: Record<string,string> = { scheduled:'Plan scheduled', sent:'Plan sent', viewed:'Plan viewed', confirmed:'Plan confirmed' };
const deliveryTone = (delivery?: Delivery|null) => delivery?.status === 'confirmed' || delivery?.status === 'viewed' ? 'completed' : delivery?.status === 'scheduled' ? 'needs_plan' : delivery?.status === 'sent' ? 'upcoming' : 'needs_plan';

function Shell({ children, active='dashboard' }:{children:React.ReactNode;active?:string}) {
  return <div className="shell">
    <aside className="sidebar">
      <Link to="/" className="brand"><span className="brand-mark"><Activity size={21}/></span><span>LetsDoIt</span></Link>
      <nav>
        <NavLink className={active==='dashboard'?'active':''} to="/"><LayoutDashboard size={19}/>Overview</NavLink>
        <NavLink className={active==='clients'?'active':''} to="/clients"><Users size={19}/>Clients</NavLink>
        <NavLink className={active==='schedule'?'active':''} to="/schedule"><CalendarDays size={19}/>Schedule</NavLink>
        <NavLink className={active==='reports'?'active':''} to="/reports"><BarChart3 size={19}/>Reports</NavLink>
      </nav>
      <TrainerMenu />
    </aside>
    <main>{children}</main>
  </div>
}

function TrainerMenu() {
  const [open,setOpen]=useState(false); const { language,setLanguage }=useLanguage(); const navigate=useNavigate();
  async function logout(){await fetch(apiUrl('auth/logout'),{method:'POST'});localStorage.removeItem('letsdoit-session');navigate('/login',{replace:true});}
  return <div className="trainer-menu"><button className="sidebar-foot trainer-trigger" aria-label="Open trainer menu" aria-expanded={open} onClick={()=>setOpen(!open)}><div className="avatar small">KO</div><div><strong>Kiki Obra</strong><span>Head trainer</span></div><ChevronDown size={16}/></button>{open&&<div className="trainer-popover"><Link to="/profile" onClick={()=>setOpen(false)}><UserRound size={16}/>Trainer profile</Link><button className="popover-button" onClick={logout}>Sign out</button><div className="language-row"><span>Language</span><div><button className={language==='hr'?'active':''} onClick={()=>setLanguage('hr')}>HR</button><button className={language==='en'?'active':''} onClick={()=>setLanguage('en')}>EN</button></div></div></div>}</div>
}

function Dashboard() {
  const [clients,setClients]=useState<Client[]|null>(null);
  const [todaySchedule,setTodaySchedule]=useState<CalendarSession[]>([]);
  const [error,setError]=useState('');
  const [query,setQuery]=useState('');
  const [filter,setFilter]=useState('all');
  const [showAdd,setShowAdd]=useState(false);
  useEffect(()=>{ fetch(apiUrl('state')).then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>{setClients(d.clients);setTodaySchedule(d.todaySchedule||[])}).catch(()=>setError('Client updates could not be loaded.')); },[]);
  const visible=useMemo(()=> (clients||[]).filter(c=>(filter==='all'||c.status===filter)&&c.name.toLowerCase().includes(query.toLowerCase())),[clients,query,filter]);
  const completed=(clients||[]).reduce((n,c)=>n+(c.sessions?.completed||0),0);
  return <Shell><div className="page dashboard-page">
    <header className="page-header"><div><p className="eyebrow">Thursday, August 13</p><h1>Good morning, Kiki</h1><p>Here’s how your clients are moving this week.</p></div><button className="primary" onClick={()=>setShowAdd(true)}><Plus size={18}/>Add client</button></header>
    <section className="metrics">
      <Metric icon={<Users/>} label="Active clients" value={String(clients?.length||0)} detail="4 training this week" />
      <Metric icon={<Check/>} label="Sessions completed" value={String(completed)} detail="78% completion rate" tone="success" />
      <Metric icon={<Sparkles/>} label="Plans to review" value={String((clients||[]).filter(c=>c.status==='needs_plan').length)} detail="Before next Monday" tone="violet" />
      <Metric icon={<CircleAlert/>} label="Need attention" value={String((clients||[]).filter(c=>c.status==='attention'||c.status==='missed').length)} detail="Down from last week" tone="warning" />
    </section>
    <section className="attention-strip"><div className="attention-icon"><TrendingUp size={20}/></div><div><strong>Weekly adjustment ready</strong><p>Maya completed every session and reported lower difficulty. A progression is ready for your review.</p></div><Link to="/clients/1/plan">Review plan <ChevronRight size={16}/></Link></section>
    <section className="today-schedule"><div className="section-title"><div><h2>Today’s schedule</h2><p>{todaySchedule.length ? `${todaySchedule.length} sessions planned` : 'No sessions scheduled today'}</p></div><Link to="/schedule">Open calendar <ChevronRight size={16}/></Link></div><div className="today-schedule-list">{todaySchedule.length?todaySchedule.map(session=><Link key={session.id} to="/schedule"><b>{session.start_time}</b><i className={`status ${session.status==='missed'?'cancelled':session.status}`}>{session.status}</i><span><strong>{session.client_name}</strong><small>{session.title} · {session.duration} min</small></span><ChevronRight size={17}/></Link>):<Link className="today-empty" to="/schedule"><Plus size={16}/>Schedule a training session</Link>}</div></section>
    <section className="client-section">
      <div className="section-head"><div><h2>Clients</h2><p>Training status and weekly momentum</p></div><div className="tools"><label className="search"><Search size={17}/><input aria-label="Search clients" placeholder="Search clients" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Filter clients" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All clients</option><option value="on_track">On track</option><option value="attention">Needs attention</option><option value="needs_plan">Plan needed</option><option value="missed">Missed sessions</option></select></div></div>
      {error&&<div className="error-state">{error} <button onClick={()=>location.reload()}>Retry</button></div>}
      {!clients&&!error&&<div className="skeleton-list"><i/><i/><i/></div>}
      {clients&&visible.length===0&&<div className="empty-state"><Users size={26}/><strong>No clients found</strong><span>Try a different search or filter.</span></div>}
      {clients&&visible.length>0&&<div className="client-table"><div className="table-head"><span>Client</span><span>This week</span><span>Goal</span><span>Status</span><span></span></div>{visible.map(c=><Link to={`/clients/${c.id}`} className="client-row" key={c.id}><span className="client-id"><i className={`avatar tone-${c.id}`}>{c.initials}</i><span><strong>{c.name}</strong><small>{c.last_active}</small></span></span><span><b>{c.sessions?.completed||0}/{Math.max(c.days_per_week,c.sessions?.completed||0)}</b><i className="progress-track"><i style={{width:`${Math.min(100,((c.sessions?.completed||0)/c.days_per_week)*100)}%`}}/></i></span><span className="goal">{c.goal}</span><span><i className={`status ${c.status}`}>{statusLabel[c.status]}</i></span><span><MoreHorizontal size={18}/></span></Link>)}</div>}
    </section>
  </div>{showAdd&&<AddClient onClose={()=>setShowAdd(false)} onCreated={c=>{setClients(v=>[...(v||[]),c]);setShowAdd(false)}}/>}</Shell>
}

function Metric({icon,label,value,detail,tone='blue'}:{icon:React.ReactNode;label:string;value:string;detail:string;tone?:string}) { return <article className="metric"><span className={`metric-icon ${tone}`}>{icon}</span><div><p>{label}</p><strong>{value}</strong><small>{detail}</small></div></article> }

function ClientDirectory() {
  const [clients,setClients]=useState<Client[]|null>(null);
  const [query,setQuery]=useState('');
  const [selected,setSelected]=useState<number[]>([]);
  const [bulkOpen,setBulkOpen]=useState(false);
  useEffect(()=>{fetch(apiUrl('state')).then(r=>r.json()).then(d=>setClients(d.clients)).catch(()=>setClients([]));},[]);
  const visible=(clients||[]).filter(c=>c.name.toLowerCase().includes(query.toLowerCase()));
  const toggle=(id:number)=>setSelected(items=>items.includes(id)?items.filter(x=>x!==id):[...items,id]);
  return <Shell active="clients"><div className="page nav-page"><header className="page-header"><div><p className="eyebrow">Client management</p><h1>All clients</h1><p>Open a profile to review assessments, workouts, and progress.</p></div><Link className="primary" to="/"><Plus size={18}/>Add client</Link></header><div className="directory-tools"><label className="search"><Search size={17}/><input autoFocus aria-label="Search clients" placeholder="Search clients" value={query} onChange={e=>setQuery(e.target.value)}/></label><span>{visible.length} clients</span></div>{selected.length>0&&<div className="bulk-bar"><span>{selected.length} selected</span><button className="primary" onClick={()=>setBulkOpen(true)}>Publish plans <ChevronRight size={16}/></button><button aria-label="Clear selected clients" onClick={()=>setSelected([])}><X size={17}/></button></div>}<section className="directory-grid">{!clients&&[1,2,3,4].map(i=><div className="directory-card skeleton-card" key={i}/>) }{visible.map(c=><div className={`directory-card ${selected.includes(c.id)?'selected':''}`} key={c.id}><button className="select-client" aria-label={`Select ${c.name}`} onClick={()=>toggle(c.id)}><span>{selected.includes(c.id)&&<Check size={13}/>}</span></button><Link to={`/clients/${c.id}`}><i className={`avatar tone-${c.id}`}>{c.initials}</i><div><i className={`status ${deliveryTone(c.delivery)}`}>{c.delivery?deliveryLabel[c.delivery.status]:'Plan ready'}</i><h2>{c.name}</h2><p>{c.goal}</p><small>{c.days_per_week} sessions weekly · {c.fitness_level}</small></div><ChevronRight size={18}/></Link></div>)}</section></div>{bulkOpen&&<SendPlanModal count={selected.length} onClose={()=>setBulkOpen(false)} onSend={async(values)=>{await fetch(apiUrl('plans/deliveries/bulk'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...values,clientIds:selected})});setBulkOpen(false);setSelected([]);fetch(apiUrl('state')).then(r=>r.json()).then(d=>setClients(d.clients));}}/>}</Shell>
}

const DAY = 86_400_000;
const CALENDAR_START = 7;
const CALENDAR_END = 22;
const CALENDAR_HOURS = CALENDAR_END - CALENDAR_START;
const HOUR_HEIGHT = 58;
const isoDate = (date: Date) => date.toISOString().slice(0, 10);
const addDays = (date: Date, days: number) => new Date(date.getTime() + days * DAY);
const startOfWeek = (date: Date) => { const copy = new Date(date); copy.setHours(12,0,0,0); return addDays(copy, (copy.getDay() + 6) % 7 * -1); };
const calendarMinutes = (time: string) => Number(time.slice(0,2)) * 60 + Number(time.slice(3,5)) - CALENDAR_START * 60;
const timeAtPointer = (event: React.DragEvent<HTMLElement>) => {
  const rect = event.currentTarget.getBoundingClientRect();
  const rawMinutes = ((event.clientY - rect.top) / HOUR_HEIGHT) * 60;
  const rounded = Math.round(rawMinutes / 15) * 15;
  const minutes = Math.max(0, Math.min(CALENDAR_HOURS * 60 - 15, rounded)) + CALENDAR_START * 60;
  return `${String(Math.floor(minutes / 60)).padStart(2,'0')}:${String(minutes % 60).padStart(2,'0')}`;
};

function SchedulePage() {
  const { language, t } = useLanguage();
  const [sessions,setSessions]=useState<CalendarSession[]>([]); const [clients,setClients]=useState<Client[]>([]); const [view,setView]=useState<'month'|'week'|'day'>('week');
  const [date,setDate]=useState(()=>new Date('2026-08-13T12:00:00')); const [clientFilter,setClientFilter]=useState('all'); const [typeFilter,setTypeFilter]=useState('all'); const [editing,setEditing]=useState<CalendarSession|null>(null); const [newSlot,setNewSlot]=useState<{date:string;time:string}|null>(null); const [dragged,setDragged]=useState<CalendarSession|null>(null);
  const locale=language==='hr'?'hr-HR':'en-US'; const load=()=>Promise.all([fetch(apiUrl('schedule')).then(r=>r.json()),fetch(apiUrl('state')).then(r=>r.json())]).then(([calendar,state])=>{setSessions(calendar);setClients(state.clients)});
  useEffect(()=>{load()},[]);
  const filtered=sessions.filter(s=>(clientFilter==='all'||String(s.client_id)===clientFilter)&&(typeFilter==='all'||s.training_type===typeFilter));
  const weekStart=startOfWeek(date); const week=Array.from({length:7},(_,i)=>addDays(weekStart,i)); const today=isoDate(new Date());
  const changeDate=(amount:number)=>setDate(view==='month'?new Date(date.getFullYear(),date.getMonth()+amount,1,12):addDays(date,amount*(view==='week'?7:1)));
  const move=async (session:CalendarSession,targetDate:string,targetTime:string)=>{ const previous=sessions; setSessions(items=>items.map(item=>item.id===session.id?{...item,scheduled_date:targetDate,start_time:targetTime}:item)); const r=await fetch(apiUrl(`sessions/${session.id}`),{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({scheduled_date:targetDate,start_time:targetTime})}); if(r.ok) load(); else {setSessions(previous);alert((await r.json()).message||'This time overlaps with another session.')} setDragged(null); };
  const dropOn=(event:React.DragEvent, targetDate:string,targetTime:string)=>{event.preventDefault();event.stopPropagation();const id=Number(event.dataTransfer.getData('text/plain'));const session=dragged||sessions.find(item=>item.id===id);if(session)move(session,targetDate,targetTime);};
  const dropOnTimeline=(event:React.DragEvent<HTMLElement>,targetDate:string)=>dropOn(event,targetDate,timeAtPointer(event));
  const slot=(day:Date,time:string)=><button className="calendar-slot" aria-label={`Schedule session at ${time}`} onClick={()=>setNewSlot({date:isoDate(day),time})} onDragOver={e=>{e.preventDefault();e.dataTransfer.dropEffect='move'}} onDrop={e=>dropOn(e,isoDate(day),time)}/>;
  const card=(session:CalendarSession,timed=false)=><button key={session.id} draggable aria-label={`${session.start_time}, ${session.client_name}, ${session.title}, ${session.duration} minutes`} style={timed?{top:`${calendarMinutes(session.start_time)/60*HOUR_HEIGHT}px`,height:`${Math.max(64,Number(session.duration||60)/60*HOUR_HEIGHT-5)}px`}:undefined} onDragStart={event=>{event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('text/plain',String(session.id));setDragged(session)}} onDragEnd={()=>setDragged(null)} onClick={()=>setEditing(session)} className={`calendar-event ${timed?'timed':''} ${session.status==='missed'?'cancelled':session.status}`}><b>{session.start_time}</b><span>{session.client_name}</span><small title={session.title}>{session.title} · {session.duration} min</small></button>;
  const monthDays=Array.from({length:42},(_,i)=>addDays(startOfWeek(new Date(date.getFullYear(),date.getMonth(),1,12)),i));
  return <Shell active="schedule"><div className="page nav-page calendar-page"><header className="page-header"><div><p className="eyebrow">Training calendar</p><h1>Schedule</h1><p>A clear view of upcoming client sessions and check-ins.</p></div><button className="primary" onClick={()=>setNewSlot({date:isoDate(date),time:'09:00'})}><Plus size={18}/>Schedule session</button></header>
    <section className="calendar-toolbar"><div className="calendar-navigation"><button aria-label="Previous period" onClick={()=>changeDate(-1)}><ChevronRight className="flip" size={18}/></button><button onClick={()=>setDate(new Date('2026-08-13T12:00:00'))}>Today</button><button aria-label="Next period" onClick={()=>changeDate(1)}><ChevronRight size={18}/></button><strong>{date.toLocaleDateString(locale,{month:'long',year:'numeric'})}</strong></div><div className="calendar-tools"><select aria-label="Filter by client" value={clientFilter} onChange={e=>setClientFilter(e.target.value)}><option value="all">All clients</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select aria-label="Filter by training type" value={typeFilter} onChange={e=>setTypeFilter(e.target.value)}><option value="all">All training types</option><option>Strength</option><option>Conditioning</option><option>Recovery</option></select><div className="view-switch" aria-label="Calendar view"><button className={view==='month'?'active':''} onClick={()=>setView('month')}>Month</button><button className={view==='week'?'active':''} onClick={()=>setView('week')}>Week</button><button className={view==='day'?'active':''} onClick={()=>setView('day')}>Day</button></div></div></section>
    {view==='month'&&<section className="month-calendar">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(day=><b key={day}>{day}</b>)}{monthDays.map(day=>{const daySessions=filtered.filter(s=>s.scheduled_date===isoDate(day)); return <div key={isoDate(day)} className={`month-day ${day.getMonth()!==date.getMonth()?'outside':''} ${isoDate(day)===today?'today':''}`} onClick={()=>setNewSlot({date:isoDate(day),time:'09:00'})} onDragOver={e=>{e.preventDefault();e.dataTransfer.dropEffect='move'}} onDrop={e=>dropOn(e,isoDate(day),dragged?.start_time||'09:00')}><span>{day.getDate()}</span>{daySessions.slice(0,3).map(s=>card(s))}{daySessions.length>3&&<small>+{daySessions.length-3} more</small>}</div>})}</section>}
    {view==='week'&&<section className="week-calendar"><div className="week-header"><span>Time</span>{week.map(day=><button key={isoDate(day)} className={isoDate(day)===today?'today':''} onClick={()=>{setDate(day);setView('day')}}><small>{day.toLocaleDateString(locale,{weekday:'short'})}</small><b>{day.getDate()}</b></button>)}</div><div className="week-body"><div className="time-axis">{Array.from({length:CALENDAR_HOURS},(_,i)=><span key={i}>{String(i+CALENDAR_START).padStart(2,'0')}:00</span>)}</div>{week.map(day=><div className="day-column" key={isoDate(day)} onDragOver={e=>{e.preventDefault();e.dataTransfer.dropEffect='move'}} onDrop={e=>dropOnTimeline(e,isoDate(day))}>{Array.from({length:CALENDAR_HOURS},(_,i)=>slot(day,`${String(i+CALENDAR_START).padStart(2,'0')}:00`))}{filtered.filter(s=>s.scheduled_date===isoDate(day)).map(s=>card(s,true))}</div>)}</div></section>}
    {view==='day'&&<section className="day-calendar"><header><div><p className="eyebrow">{date.toLocaleDateString(locale,{weekday:'long'})}</p><h2>{date.toLocaleDateString(locale,{day:'numeric',month:'long'})}</h2></div><span>{filtered.filter(s=>s.scheduled_date===isoDate(date)).length} sessions</span></header><div className="day-timeline" onDragOver={e=>{e.preventDefault();e.dataTransfer.dropEffect='move'}} onDrop={e=>dropOnTimeline(e,isoDate(date))}><div className="day-hours">{Array.from({length:CALENDAR_HOURS},(_,i)=>{const time=`${String(i+CALENDAR_START).padStart(2,'0')}:00`; return <div key={time}><b>{time}</b>{slot(date,time)}</div>})}</div><div className="day-events">{filtered.filter(s=>s.scheduled_date===isoDate(date)).map(s=>card(s,true))}</div></div></section>}
    <section className="calendar-legend"><span><i className="upcoming"/>Upcoming</span><span><i className="completed"/>Completed</span><span><i className="cancelled"/>Cancelled</span><span>Drag a session to move it</span></section>
  </div>{(editing||newSlot)&&<SessionModal session={editing} slot={newSlot} clients={clients} onClose={()=>{setEditing(null);setNewSlot(null)}} onSaved={()=>{setEditing(null);setNewSlot(null);load()}}/>}</Shell>
}

function SessionModal({session,slot,clients,onClose,onSaved}:{session:CalendarSession|null;slot:{date:string;time:string}|null;clients:Client[];onClose:()=>void;onSaved:()=>void}) {
  const [form,setForm]=useState({client_id:String(session?.client_id||clients[0]?.id||''),title:session?.title||'',scheduled_date:session?.scheduled_date||slot?.date||'2026-08-13',start_time:session?.start_time||slot?.time||'09:00',duration:String(session?.duration||60),training_type:session?.training_type||'Strength',status:session?.status==='missed'?'cancelled':session?.status||'upcoming',recurrence_rule:session?.recurrence_rule||'',notes:session?.notes||''}); const [error,setError]=useState('');
  const set=(key:string,value:string)=>setForm(data=>({...data,[key]:value})); async function submit(e:FormEvent){e.preventDefault();const r=await fetch(apiUrl(session?`sessions/${session.id}`:'schedule'),{method:session?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,client_id:Number(form.client_id),duration:Number(form.duration)})});if(r.ok)onSaved();else setError((await r.json()).message||'Unable to save this session.');}
  return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><form className="modal schedule-modal" onSubmit={submit}><div className="modal-title"><div><span>{session?'Session details':'New training session'}</span><h2>{session?'Review or update this training':'Schedule a client session'}</h2></div><button type="button" aria-label="Close" onClick={onClose}><X/></button></div>{error&&<div className="error-state">{error}</div>}<div className="form-grid"><Field label="Client"><select autoFocus value={form.client_id} onChange={e=>set('client_id',e.target.value)}>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Training type"><select value={form.training_type} onChange={e=>set('training_type',e.target.value)}><option>Strength</option><option>Conditioning</option><option>Recovery</option></select></Field><Field label="Session name" wide><input required value={form.title} placeholder="e.g. Full body strength" onChange={e=>set('title',e.target.value)}/></Field><Field label="Date"><input required type="date" value={form.scheduled_date} onChange={e=>set('scheduled_date',e.target.value)}/></Field><Field label="Start time"><input required type="time" value={form.start_time} onChange={e=>set('start_time',e.target.value)}/></Field><Field label="Duration (minutes)"><input required min="15" step="15" type="number" value={form.duration} onChange={e=>set('duration',e.target.value)}/></Field><Field label="Status"><select value={form.status} onChange={e=>set('status',e.target.value)}><option value="upcoming">Upcoming</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></Field><Field label="Repeat" wide><select value={form.recurrence_rule} onChange={e=>set('recurrence_rule',e.target.value)}><option value="">Does not repeat</option><option value="weekly:1,3">Every Monday and Wednesday</option><option value="weekly:1">Every Monday</option><option value="weekly:3">Every Wednesday</option></select></Field><Field label="Notes" wide><textarea value={form.notes} onChange={e=>set('notes',e.target.value)} placeholder="Training notes or focus for this session"/></Field></div><div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary">{session?'Save changes':'Schedule session'} <ChevronRight size={16}/></button></div></form></div>
}

function ReportsPage() {
  return <Shell active="reports"><div className="page nav-page"><header className="page-header"><div><p className="eyebrow">Progress reporting</p><h1>Reports</h1><p>Quick signals from your client roster, ready for coaching decisions.</p></div><button className="secondary">This week <ChevronDown size={16}/></button></header><section className="metrics report-metrics"><Metric icon={<Check/>} label="Completion rate" value="78%" detail="Up 6% from last week" tone="success"/><Metric icon={<Flame/>} label="Training minutes" value="342" detail="Across 7 sessions" tone="warning"/><Metric icon={<TrendingUp/>} label="Personal records" value="3" detail="This month" tone="violet"/><Metric icon={<UserRound/>} label="Check-ins due" value="2" detail="Jordan and Marcus" /></section><section className="report-panel"><div className="section-title"><div><h2>Coaching signals</h2><p>What deserves attention this week</p></div></div><div className="report-row"><i className="status completed">Ready to progress</i><div><strong>Maya Chen</strong><p>All sessions completed below target difficulty. Consider a 2.5% primary lift increase.</p></div><Link to="/clients/1/plan">Review plan <ChevronRight size={16}/></Link></div><div className="report-row"><i className="status attention">Follow up</i><div><strong>Jordan Blake</strong><p>Difficulty rose while session completion dipped. Check recovery before increasing volume.</p></div><Link to="/clients/2">Open profile <ChevronRight size={16}/></Link></div></section></div></Shell>
}

function TrainerProfile() {
  const { language,setLanguage }=useLanguage();
  return <Shell><div className="page nav-page"><header className="page-header"><div><p className="eyebrow">Trainer account</p><h1>Kiki Obra</h1><p>Manage your workspace preferences and language.</p></div></header><section className="profile-settings"><div><h2>Language</h2><p>Croatian is the default for new users. Your choice is saved for future visits.</p></div><div className="language-choice"><button className={language==='hr'?'selected':''} onClick={()=>setLanguage('hr')}>Hrvatski <small>Default</small></button><button className={language==='en'?'selected':''} onClick={()=>setLanguage('en')}>English</button></div></section></div></Shell>
}

function AddClient({onClose,onCreated}:{onClose:()=>void;onCreated:(c:Client)=>void}) {
  const { language }=useLanguage(); const [step,setStep]=useState(1); const [saving,setSaving]=useState(false); const [data,setData]=useState<Record<string,string>>({fitness_level:'Beginner',days_per_week:'3',language});
  const set=(k:string,v:string)=>setData(d=>({...d,[k]:v}));
  async function submit(e:FormEvent){e.preventDefault();if(step<2){setStep(2);return}setSaving(true);const r=await fetch(apiUrl('clients'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(r.ok)onCreated(await r.json());else setSaving(false)}
  return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><form className="modal" onSubmit={submit}><div className="modal-title"><div><span>New client assessment</span><h2>{step===1?'Start with the basics':'Training profile'}</h2></div><button type="button" aria-label="Close" onClick={onClose}><X/></button></div><div className="steps"><i className="done">1</i><span className={step===2?'filled':''}/><i className={step===2?'done':''}>2</i><small>Step {step} of 2</small></div>
    {step===1?<div className="form-grid"><Field label="Full name"><input autoFocus required value={data.name||''} onChange={e=>set('name',e.target.value)} placeholder="Client name"/></Field><Field label="Email"><input type="email" value={data.email||''} onChange={e=>set('email',e.target.value)} placeholder="client@example.com"/></Field><Field label="Age"><input type="number" required value={data.age||''} onChange={e=>set('age',e.target.value)}/></Field><Field label="Fitness level"><select value={data.fitness_level} onChange={e=>set('fitness_level',e.target.value)}><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></Field><Field label="Weight (kg)"><input type="number" step=".1" required value={data.weight||''} onChange={e=>set('weight',e.target.value)}/></Field><Field label="Height (cm)"><input type="number" required value={data.height||''} onChange={e=>set('height',e.target.value)}/></Field><Field label="Client language" wide><select value={data.language} onChange={e=>set('language',e.target.value)}><option value="hr">Hrvatski</option><option value="en">English</option></select></Field><Field label="Primary goal" wide><input required value={data.goal||''} onChange={e=>set('goal',e.target.value)} placeholder="Build strength, improve mobility…"/></Field></div>:<div className="form-grid"><Field label="Current physical condition" wide><textarea autoFocus required value={data.condition||''} onChange={e=>set('condition',e.target.value)} placeholder="Current activity, recovery, general readiness"/></Field><Field label="Injuries or limitations" wide><textarea value={data.limitations||''} onChange={e=>set('limitations',e.target.value)} placeholder="Include movements that cause discomfort"/></Field><Field label="Available equipment"><input required value={data.equipment||''} onChange={e=>set('equipment',e.target.value)} placeholder="Full gym, dumbbells…"/></Field><Field label="Preferred workouts"><input required value={data.preferences||''} onChange={e=>set('preferences',e.target.value)} placeholder="Strength, cycling…"/></Field><Field label="Training days per week" wide><div className="day-picker">{[2,3,4,5].map(n=><button type="button" className={data.days_per_week===String(n)?'selected':''} onClick={()=>set('days_per_week',String(n))} key={n}>{n} days</button>)}</div></Field></div>}
    <div className="modal-actions">{step===2&&<button type="button" className="secondary" onClick={()=>setStep(1)}>Back</button>}<button className="primary" disabled={saving}>{step===1?'Continue':'Create client and plan'}<ChevronRight size={17}/></button></div></form></div>
}

function Field({label,wide=false,children}:{label:string;wide?:boolean;children:React.ReactNode}) { return <label className={wide?'field wide':'field'}><span>{label}</span>{children}</label> }

type AuthUser = { id:number; email:string; display_name:string; role:'trainer'|'client'; client_id:number|null };

function Login() {
  const navigate=useNavigate(); const location=useLocation(); const {language,setLanguage}=useLanguage(); const [email,setEmail]=useState('trainer@letsdoit.app'); const [password,setPassword]=useState('Trainer2026!'); const [error,setError]=useState(''); const [saving,setSaving]=useState(false);
  useEffect(()=>{const params=new URLSearchParams(location.search);const code=params.get('code');const ssoError=params.get('sso_error');if(ssoError){setError(ssoError==='not_allowed'?'This Google account is not linked to LetsDoIt.':'Google sign-in was not completed.');return;}if(!code)return;setSaving(true);fetch(apiUrl('auth/exchange'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code})}).then(async response=>({ok:response.ok,data:await response.json()})).then(({ok,data})=>{if(!ok){setError(data.message||'Google sign-in expired.');setSaving(false);return;}localStorage.setItem('letsdoit-session',data.token);navigate(data.user.role==='client'?'/client':'/',{replace:true});}).catch(()=>{setError('Google sign-in could not be completed.');setSaving(false);});},[location.search,navigate]);
  async function submit(event:FormEvent){event.preventDefault();setSaving(true);setError('');const response=await fetch(apiUrl('auth/login'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const data=await response.json();setSaving(false);if(!response.ok){setError(data.message||'Unable to sign in.');return;}localStorage.setItem('letsdoit-session',data.token);navigate(data.user.role==='client'?'/client':'/',{replace:true});}
  const copy=language==='hr'?{eyebrow:'Dobro došli',title:'Vaš trening, na jednom mjestu',body:'Prijavite se za svoj osobni raspored, plan i napredak.',email:'E-pošta',password:'Lozinka',submit:'Prijavi se',demo:'Demo računi: trainer@letsdoit.app ili maya@example.com'}:{eyebrow:'Welcome back',title:'Your training, in one place',body:'Sign in to reach your personal schedule, plan, and progress.',email:'Email',password:'Password',submit:'Sign in',demo:'Demo accounts: trainer@letsdoit.app or maya@example.com'};
  return <main className="login-page"><section className="login-card"><Link className="portal-brand login-brand" to="/login"><Activity size={20}/>LetsDoIt</Link><div className="language-choice login-language"><button className={language==='hr'?'selected':''} onClick={()=>setLanguage('hr')}>Hrvatski</button><button className={language==='en'?'selected':''} onClick={()=>setLanguage('en')}>English</button></div><p className="eyebrow">{copy.eyebrow}</p><h1>{copy.title}</h1><p>{copy.body}</p><a className="google-button" href={apiUrl('auth/google')}>Continue with Google</a><div className="login-divider"><span>or</span></div><form onSubmit={submit}><Field label={copy.email}><input autoFocus type="email" value={email} onChange={event=>setEmail(event.target.value)} required/></Field><Field label={copy.password}><input type="password" value={password} onChange={event=>setPassword(event.target.value)} required/></Field>{error&&<p className="login-error">{error}</p>}<button className="primary" disabled={saving}>{copy.submit}<ChevronRight size={17}/></button></form><small>{copy.demo} · Trainer2026! / Client2026!</small></section></main>
}

function AuthGate({children,role}:{children:React.ReactNode;role:'trainer'|'client'}) {
  const location=useLocation(); const [user,setUser]=useState<AuthUser|null|undefined>(undefined);
  useEffect(()=>{fetch(apiUrl('auth/me')).then(response=>response.ok?response.json():null).then(setUser).catch(()=>setUser(null));},[]);
  if(user===undefined)return <div className="loading-portal">Loading…</div>;
  if(!user)return <Navigate to="/login" replace state={{from:location.pathname}}/>;
  if(user.role!==role)return <Navigate to={user.role==='client'?'/client':'/'} replace/>;
  return <>{children}</>;
}

function ClientPage({planOnly=false}:{planOnly?:boolean}) {
  const { language }=useLanguage(); const locale=language==='hr'?'hr-HR':'en-US'; const {clientId}=useParams(); const navigate=useNavigate(); const [data,setData]=useState<ClientDetail|null>(null); const [error,setError]=useState(''); const [tab,setTab]=useState<'overview'|'workouts'|'progress'>('overview'); const [logSession,setLogSession]=useState<Session|null>(null); const [progressOpen,setProgressOpen]=useState(false);
  const load=()=>fetch(apiUrl(`clients/${clientId}`)).then(r=>{if(!r.ok)throw Error();return r.json()}).then(setData).catch(()=>setError('This client profile could not be loaded.'));
  useEffect(()=>{load()},[clientId]);
  if(error)return <Shell active="clients"><div className="error-state page">{error} <button onClick={load}>Retry</button></div></Shell>;
  if(!data)return <Shell active="clients"><div className="page"><div className="profile-skeleton"/></div></Shell>;
  if(planOnly&&data.plan)return <PlanReview data={data} onReload={load}/>;
  const {client,plan,delivery,sessions,progress,analysis}=data; const latest=progress.at(-1); const previous=progress.at(-2);
  return <Shell active="clients"><div className="page profile-page"><button className="back-link" onClick={()=>navigate('/clients')}><ArrowLeft size={17}/>All clients</button><header className="profile-header"><div className={`avatar large tone-${client.id}`}>{client.initials}</div><div><div className="profile-name"><h1>{client.name}</h1><i className={`status ${client.status}`}>{statusLabel[client.status]}</i></div><p>{client.email} · {client.age} years · {client.fitness_level}</p><span className="goal-line"><Sparkles size={15}/>{client.goal}</span>{delivery&&<span className="delivery-chip"><Check size={14}/>{deliveryLabel[delivery.status]}{delivery.confirmed_at?' · Schedule confirmed':''}</span>}</div><div className="profile-actions"><Link className="secondary" to={`/client/${client.id}`}>Client view</Link><Link className="primary" to={`/clients/${client.id}/plan`}>Review weekly plan</Link></div></header>
    <div className="tabs"><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}>Overview</button><button className={tab==='workouts'?'active':''} onClick={()=>setTab('workouts')}>Workouts</button><button className={tab==='progress'?'active':''} onClick={()=>setTab('progress')}>Progress</button></div>
    {tab==='overview'&&<><section className="summary-grid"><article><span>Weekly completion</span><strong>{analysis.completion}%</strong><div className="bar"><i style={{width:`${analysis.completion}%`}}/></div><small>{sessions.filter(s=>s.status==='completed').length} sessions completed</small></article><article><span>Current weight</span><strong>{latest?.weight||client.weight} kg</strong><small className="positive">{previous&&latest?`${(latest.weight-previous.weight).toFixed(1)} kg since last check-in`:'Baseline recorded'}</small></article><article><span>Squat best</span><strong>{latest?.squat_max||'—'} kg</strong><small className="positive">Personal record this month</small></article><article><span>Average difficulty</span><strong>{analysis.avgDifficulty || '—'}<em>/10</em></strong><small>From completed sessions</small></article></section>
      <section className="profile-columns"><div><div className="section-title"><div><h2>This week</h2><p>{plan?.week_label}</p></div><Link to={`/clients/${client.id}/plan`}>Edit plan</Link></div><div className="session-list">{sessions.slice(0,4).map(s=><button key={s.id} onClick={()=>s.status!=='missed'&&setLogSession(s)}><i className={`session-state ${s.status}`}>{s.status==='completed'?<Check/>:s.status==='missed'?<X/>:<Dumbbell/>}</i><span><strong>{s.title}</strong><small>{new Date(s.scheduled_date+'T12:00:00').toLocaleDateString(locale,{weekday:'long',month:'short',day:'numeric'})}</small></span><i className={`status ${s.status}`}>{s.status}</i><ChevronRight size={17}/></button>)}</div></div><div><div className="section-title"><div><h2>Coach insight</h2><p>Next week’s recommendation</p></div></div><article className="insight-card"><span><Sparkles size={18}/>Weekly analysis</span><p>{analysis.suggestion}</p><div><b>Based on</b><small>{analysis.completion}% completion · {analysis.avgDifficulty}/10 difficulty · recent feedback</small></div><Link to={`/clients/${client.id}/plan`}>Review adjustment <ChevronRight size={16}/></Link></article></div></section></>}
    {tab==='workouts'&&<section className="tab-panel"><div className="section-title"><div><h2>Workout history</h2><p>Completed and upcoming sessions</p></div></div><div className="history-list">{sessions.map(s=><button key={s.id} onClick={()=>setLogSession(s)}><span><i className={`session-state ${s.status}`}>{s.status==='completed'?<Check/>:<Dumbbell/>}</i><span><strong>{s.title}</strong><small>{s.scheduled_date}</small></span></span><span><b>{s.duration?`${s.duration} min`:'Not logged'}</b><i className={`status ${s.status}`}>{s.status}</i><ChevronRight size={17}/></span></button>)}</div></section>}
    {tab==='progress'&&<section className="tab-panel"><div className="section-title"><div><h2>Progress over time</h2><p>Measurements, strength, feedback, and assessment results</p></div><button className="primary" onClick={()=>setProgressOpen(true)}><Plus size={17}/>Add check-in</button></div><ProgressView rows={progress}/></section>}
  </div>{logSession&&<LogWorkout session={logSession} onClose={()=>setLogSession(null)} onSaved={()=>{setLogSession(null);load()}}/>}{progressOpen&&<ProgressModal clientId={client.id} onClose={()=>setProgressOpen(false)} onSaved={()=>{setProgressOpen(false);load()}}/>}</Shell>
}

function ClientWorkspace() {
  const {language,setLanguage}=useLanguage(); const locale=language==='hr'?'hr-HR':'en-US'; const [data,setData]=useState<any>(null); const [tab,setTab]=useState<'today'|'plan'|'calendar'|'progress'|'history'>('today'); const [workout,setWorkout]=useState<Session|null>(null); const [progressOpen,setProgressOpen]=useState(false); const [notice,setNotice]=useState('');
  const load=()=>fetch(apiUrl('client/me')).then(response=>response.ok?response.json():Promise.reject()).then(setData);
  useEffect(()=>{load().catch(()=>setNotice(language==='hr'?'Nije moguće učitati vaš prostor.':'Your workspace could not be loaded.'));},[]);
  async function logout(){await fetch(apiUrl('auth/logout'),{method:'POST'});localStorage.removeItem('letsdoit-session');location.assign('./login');}
  if(!data)return <div className="client-portal loading-portal">{notice||'Loading your training…'}</div>;
  const copy=language==='hr'?{today:'Danas',plan:'Tjedni plan',calendar:'Raspored',progress:'Napredak',history:'Povijest',hello:'Bok',next:'Sljedeći trening',none:'Danas nema zakazanog treninga',upcoming:'Nadolazeći treninzi',log:'Zapiši trening',done:'Završi trening',measure:'Dodaj mjerenje',logout:'Odjava',available:'Plan je dostupan',send:'Trener još nije objavio novi plan',photo:'Poveznica na fotografiju'}:{today:'Today',plan:'Weekly plan',calendar:'Schedule',progress:'Progress',history:'History',hello:'Hi',next:'Next workout',none:'No workout is scheduled for today',upcoming:'Upcoming workouts',log:'Log workout',done:'Complete workout',measure:'Add check-in',logout:'Sign out',available:'Your plan is ready',send:'Your coach has not published a new plan yet',photo:'Photo link'};
  const upcoming=data.sessions.filter((session:Session)=>session.status==='upcoming').sort((a:Session,b:Session)=>a.scheduled_date.localeCompare(b.scheduled_date)); const today=upcoming.find((session:Session)=>session.scheduled_date===new Date().toISOString().slice(0,10))||upcoming[0]; const visibleSessions=tab==='history'?data.sessions.filter((session:Session)=>session.status==='completed'):upcoming;
  return <div className="client-portal"><header><Link to="/client" className="portal-brand"><Activity size={19}/>LetsDoIt</Link><div className="portal-actions"><span>{data.client.name}</span><button onClick={()=>setLanguage(language==='hr'?'en':'hr')}>{language==='hr'?'EN':'HR'}</button><button onClick={logout}>{copy.logout}</button></div></header><main><p className="eyebrow">{copy.today}</p><h1>{copy.hello}, {data.client.name.split(' ')[0]}</h1><p className="portal-intro">{language==='hr'?'Ovo je vaš osobni prostor za trening, raspored i napredak.':'This is your personal space for training, schedule, and progress.'}</p><nav className="portal-tabs">{([['today',copy.today],['plan',copy.plan],['calendar',copy.calendar],['progress',copy.progress],['history',copy.history]] as const).map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav>
    {tab==='today'&&<><section className="portal-status"><span><Check size={18}/>{data.plan?copy.available:copy.send}</span><p>{data.plan?data.plan.week_label:''}</p></section><section className="client-today"><div><p className="eyebrow">{copy.next}</p><h2>{today?.title||copy.none}</h2>{today&&<p>{new Date(today.scheduled_date+'T12:00:00').toLocaleDateString(locale,{weekday:'long',month:'long',day:'numeric'})} · {today.duration||0} min</p>}</div>{today&&<button className="primary" onClick={()=>setWorkout(today)}>{copy.log}<ChevronRight size={16}/></button>}</section><section className="portal-history"><h2>{copy.upcoming}</h2>{upcoming.slice(0,4).map((session:Session)=><div key={session.id}><i className="session-state upcoming"><Dumbbell/></i><span><strong>{session.title}</strong><small>{new Date(session.scheduled_date+'T12:00:00').toLocaleDateString(locale,{weekday:'short',month:'short',day:'numeric'})}</small></span><button className="icon-action" aria-label={copy.log} onClick={()=>setWorkout(session)}><ChevronRight size={17}/></button></div>)}</section></>}
    {tab==='plan'&&(!data.plan?<section className="portal-empty"><Clock3 size={27}/><h2>{copy.send}</h2></section>:<section className="portal-workouts">{data.plan.workouts.map((item:Workout)=><article key={item.id}><div><span>{item.day}</span><h2>{item.title}</h2><p>{item.duration} min · {item.focus}</p></div><ul>{item.exercises.map(exercise=><li key={exercise.name}><strong>{exercise.name}</strong><span>{exercise.sets} × {exercise.reps} · {exercise.intensity}</span></li>)}</ul></article>)}</section>)}
    {tab==='calendar'&&<section className="portal-history"><h2>{copy.calendar}</h2>{upcoming.map((session:Session)=><div key={session.id}><i className="session-state upcoming"><CalendarDays/></i><span><strong>{session.title}</strong><small>{new Date(session.scheduled_date+'T12:00:00').toLocaleDateString(locale,{weekday:'long',month:'long',day:'numeric'})} · {(session as any).start_time}</small></span><i className="status upcoming">{language==='hr'?'zakazano':'scheduled'}</i></div>)}</section>}
    {tab==='progress'&&<section className="tab-panel"><div className="section-title"><div><h2>{copy.progress}</h2><p>{language==='hr'?'Mjerenja, osobni rekordi i povratne informacije.':'Measurements, personal records, and feedback.'}</p></div><button className="primary" onClick={()=>setProgressOpen(true)}><Plus size={17}/>{copy.measure}</button></div><ProgressView rows={data.progress}/></section>}
    {tab==='history'&&<section className="portal-history"><h2>{copy.history}</h2>{visibleSessions.map((session:Session)=><div key={session.id}><i className="session-state completed"><Check/></i><span><strong>{session.title}</strong><small>{session.scheduled_date} · {session.duration||0} min · {session.difficulty||'—'}/10</small></span><i className="status completed">{language==='hr'?'završeno':'completed'}</i></div>)}</section>}
  </main>{workout&&<ClientWorkoutLog session={workout} plan={data.plan} onClose={()=>setWorkout(null)} onSaved={()=>{setWorkout(null);setNotice(language==='hr'?'Trening je spremljen.':'Workout saved.');load();}}/>}{progressOpen&&<ClientProgressForm onClose={()=>setProgressOpen(false)} onSaved={()=>{setProgressOpen(false);load();}} photoLabel={copy.photo}/>}</div>
}

function ClientWorkoutLog({session,plan,onClose,onSaved}:{session:Session;plan:Plan|null;onClose:()=>void;onSaved:()=>void}) { const {language}=useLanguage(); const [duration,setDuration]=useState(String(session.duration||45)); const [difficulty,setDifficulty]=useState('6'); const [notes,setNotes]=useState(''); const [saving,setSaving]=useState(false); const workout=plan?.workouts.find(item=>item.title===session.title); const exercises=workout?.exercises||[]; const [records,setRecords]=useState<Record<string,{sets:string;reps:string;load:string}>>(()=>Object.fromEntries(exercises.map(item=>[item.name,{sets:String(item.sets),reps:item.reps,load:''}])));
  async function submit(event:FormEvent){event.preventDefault();setSaving(true);await fetch(apiUrl(`client/sessions/${session.id}/complete`),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({duration:Number(duration),difficulty:Number(difficulty),notes,performance:exercises.map(exercise=>({exercise:exercise.name,...records[exercise.name]}))})});setSaving(false);onSaved();}
  return <div className="modal-backdrop"><form className="modal compact" onSubmit={submit}><div className="modal-title"><div><span>{language==='hr'?'Zapis treninga':'Workout log'}</span><h2>{session.title}</h2></div><button type="button" aria-label="Close" onClick={onClose}><X/></button></div><div className="form-grid"><Field label={language==='hr'?'Trajanje u minutama':'Duration in minutes'}><input autoFocus type="number" required value={duration} onChange={event=>setDuration(event.target.value)}/></Field><Field label={language==='hr'?'Težina 1–10':'Difficulty 1–10'}><input type="number" min="1" max="10" required value={difficulty} onChange={event=>setDifficulty(event.target.value)}/></Field>{exercises.map(exercise=><div className="exercise-log" key={exercise.name}><strong>{exercise.name}</strong><input aria-label="Sets" placeholder={language==='hr'?'Serije':'Sets'} value={records[exercise.name]?.sets||''} onChange={event=>setRecords(rows=>({...rows,[exercise.name]:{...rows[exercise.name],sets:event.target.value}}))}/><input aria-label="Reps" placeholder={language==='hr'?'Ponavljanja':'Reps'} value={records[exercise.name]?.reps||''} onChange={event=>setRecords(rows=>({...rows,[exercise.name]:{...rows[exercise.name],reps:event.target.value}}))}/><input aria-label="Weight" placeholder={language==='hr'?'Težina':'Weight'} value={records[exercise.name]?.load||''} onChange={event=>setRecords(rows=>({...rows,[exercise.name]:{...rows[exercise.name],load:event.target.value}}))}/></div>)}<Field label={language==='hr'?'Bilješke za trenera':'Notes for your coach'} wide><textarea value={notes} onChange={event=>setNotes(event.target.value)}/></Field></div><div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>{language==='hr'?'Odustani':'Cancel'}</button><button className="primary" disabled={saving}>{language==='hr'?'Završi trening':'Complete workout'}<Check size={16}/></button></div></form></div> }

function ClientProgressForm({onClose,onSaved,photoLabel}:{onClose:()=>void;onSaved:()=>void;photoLabel:string}) { const {language}=useLanguage(); const [data,setData]=useState<Record<string,string>>({}); async function submit(event:FormEvent){event.preventDefault();await fetch(apiUrl('client/progress'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});onSaved();} const field=(key:string,label:string)=><Field label={label}><input type="number" step=".1" value={data[key]||''} onChange={event=>setData(values=>({...values,[key]:event.target.value}))}/></Field>;return <div className="modal-backdrop"><form className="modal compact" onSubmit={submit}><div className="modal-title"><div><span>{language==='hr'?'Napredak':'Progress'}</span><h2>{language==='hr'?'Novi unos':'New check-in'}</h2></div><button type="button" aria-label="Close" onClick={onClose}><X/></button></div><div className="form-grid">{field('weight',language==='hr'?'Težina kg':'Weight kg')}{field('waist',language==='hr'?'Struk cm':'Waist cm')}{field('body_fat',language==='hr'?'Tjelesna mast %':'Body fat %')}{field('squat_max',language==='hr'?'Najbolji čučanj kg':'Best squat kg')}<Field label={photoLabel} wide><input type="url" placeholder="https://…" value={data.photo_url||''} onChange={event=>setData(values=>({...values,photo_url:event.target.value}))}/></Field><Field label={language==='hr'?'Kako se osjećate?':'How do you feel?'} wide><textarea value={data.feedback||''} onChange={event=>setData(values=>({...values,feedback:event.target.value}))}/></Field></div><div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>{language==='hr'?'Odustani':'Cancel'}</button><button className="primary">{language==='hr'?'Spremi':'Save'}</button></div></form></div> }

function ClientView() {
  const { language }=useLanguage(); const locale=language==='hr'?'hr-HR':'en-US'; const {clientId}=useParams(); const [data,setData]=useState<ClientDetail|null>(null); const [feedback,setFeedback]=useState(''); const [confirmed,setConfirmed]=useState(false);
  const load=()=>fetch(apiUrl(`clients/${clientId}`)).then(r=>r.json()).then(setData);
  useEffect(()=>{load()},[clientId]);
  useEffect(()=>{if(data?.delivery && ['sent','viewed'].includes(data.delivery.status)) fetch(apiUrl(`deliveries/${data.delivery.id}/view`),{method:'POST'}).then(load);},[data?.delivery?.id]);
  if(!data)return <div className="client-portal loading-portal">Loading your plan…</div>;
  const {client,plan,delivery,sessions}=data; const unavailable=!delivery || delivery.status==='scheduled';
  async function confirm(){if(!delivery)return;await fetch(apiUrl(`deliveries/${delivery.id}/confirm`),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({feedback})});setConfirmed(true);load();}
  return <div className="client-portal"><header><Link to={`/clients/${client.id}`} className="portal-brand"><Activity size={19}/>LetsDoIt</Link><span>{client.name}</span></header><main><p className="eyebrow">Your training plan</p><h1>Week of {plan?.week_label}</h1><p className="portal-intro">Your coach prepared this plan around your current goals, equipment, and recovery.</p>{unavailable?<section className="portal-empty"><Clock3 size={27}/><h2>Your next plan is on its way</h2><p>It will be available {delivery?new Date(delivery.available_at).toLocaleString(locale,{weekday:'long',month:'long',day:'numeric',hour:'numeric',minute:'2-digit'}):'once your coach publishes it'}.</p></section>:<><section className="portal-status"><span><Check size={18}/>Plan available</span><p>{delivery?.confirmed_at||confirmed?'You confirmed this schedule. Your coach has your note.':'Please review your week and confirm that the schedule works for you.'}</p></section><section className="portal-workouts">{plan?.workouts.map(w=><article key={w.id}><div><span>{w.day}</span><h2>{w.title}</h2><p>{w.duration} min · {w.focus}</p></div><ul>{w.exercises.map(e=><li key={e.name}><strong>{e.name}</strong><span>{e.sets} sets · {e.reps} · {e.intensity}</span></li>)}</ul></article>)}</section>{!delivery?.confirmed_at&&!confirmed&&<section className="confirm-card"><div><h2>Does this schedule work?</h2><p>Confirm your week or leave a note for your coach.</p></div><textarea value={feedback} onChange={e=>setFeedback(e.target.value)} placeholder="Optional feedback about this plan"/><button className="primary" onClick={confirm}>Confirm schedule <Check size={17}/></button></section>}<section className="portal-history"><h2>Recent sessions</h2>{sessions.slice(0,3).map(s=><div key={s.id}><i className={`session-state ${s.status}`}>{s.status==='completed'?<Check/>:<Dumbbell/>}</i><span><strong>{s.title}</strong><small>{s.scheduled_date}</small></span><i className={`status ${s.status}`}>{s.status}</i></div>)}</section></>}</main></div>
}

function ProgressView({rows}:{rows:Progress[]}) { const { language }=useLanguage(); const locale=language==='hr'?'hr-HR':'en-US'; const max=Math.max(...rows.map(r=>r.squat_max||0),1); return <div className="progress-layout"><article className="chart-card"><span>Strength trend · squat</span><div className="chart">{rows.map(r=><div key={r.id}><i style={{height:`${Math.max(15,(r.squat_max/max)*100)}%`}}/><b>{r.squat_max||'—'} kg</b><small>{new Date(r.recorded_date+'T12:00:00').toLocaleDateString(locale,{month:'short'})}</small></div>)}</div></article><article className="measure-card"><span>Latest measurements</span>{rows.length?<><div><b>Weight</b><strong>{rows.at(-1)!.weight} kg</strong></div><div><b>Waist</b><strong>{rows.at(-1)!.waist} cm</strong></div><div><b>Body fat</b><strong>{rows.at(-1)!.body_fat}%</strong></div><blockquote>“{rows.at(-1)!.feedback}”</blockquote></>:<p>No measurements yet.</p>}</article><article className="photo-card"><span>Progress photos</span><div className="photo-placeholders"><i>Jun</i><i>Jul</i><button aria-label="Add progress photo"><Plus/></button></div><small>Add photos privately with each check-in.</small></article></div> }

function PlanReview({data,onReload}:{data:ClientDetail;onReload:()=>void}) { const { language }=useLanguage(); const locale=language==='hr'?'hr-HR':'en-US'; const navigate=useNavigate(); const [plan,setPlan]=useState(data.plan!); const [open,setOpen]=useState(0); const [saving,setSaving]=useState(false); const [saved,setSaved]=useState(false); const [sendOpen,setSendOpen]=useState(false); const [delivery,setDelivery]=useState<Delivery|null>(data.delivery);
  function editExercise(wi:number,ei:number,key:keyof Exercise,value:string|number){setPlan(p=>({...p,workouts:p.workouts.map((w,i)=>i===wi?{...w,exercises:w.exercises.map((e,j)=>j===ei?{...e,[key]:value}:e)}:w)}))}
  async function save(){setSaving(true);await fetch(apiUrl(`plans/${plan.id}`),{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:plan.status,workouts:plan.workouts})});setSaving(false);setSaved(true);setTimeout(()=>setSaved(false),2500)}
  async function publish(values:{channel:string;available_at:string}){await save();const response=await fetch(apiUrl(`plans/${plan.id}/delivery`),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(values)});if(response.ok){setDelivery(await response.json());setPlan(p=>({...p,status:'assigned'}));setSendOpen(false);onReload();}}
  return <Shell active="clients"><div className="page plan-page"><button className="back-link" onClick={()=>navigate(`/clients/${data.client.id}`)}><ArrowLeft size={17}/>{data.client.name}</button><header className="plan-header"><div><p className="eyebrow">Weekly plan · {plan.week_label}</p><h1>Review before publishing</h1><p>Make any final changes, then choose when this plan becomes available to {data.client.name.split(' ')[0]}.</p></div><div className="plan-actions"><button className="secondary" onClick={save} disabled={saving}>Save changes</button><button className="primary" onClick={()=>setSendOpen(true)}><Check size={18}/>{delivery?'Update delivery':'Publish plan'}</button></div></header>{delivery&&<div className="delivery-state"><i className={`status ${deliveryTone(delivery)}`}>{deliveryLabel[delivery.status]}</i><span>{delivery.status==='scheduled'?`Available ${new Date(delivery.available_at).toLocaleString(locale,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}`:delivery.status==='confirmed'?'Client confirmed their schedule':delivery.status==='viewed'?'Client has viewed this plan':'Available in the client workspace'}</span><button onClick={()=>setSendOpen(true)}>Change</button></div>}<div className="plan-banner"><Sparkles size={20}/><div><strong>Suggested from this week’s performance</strong><p>{data.analysis.suggestion}</p></div><span>Trainer review required</span></div>
    <section className="workout-editor"><div className="editor-head"><div><h2>{plan.workouts.length} training days</h2><p>{plan.workouts.reduce((n,w)=>n+w.duration,0)} planned minutes · tailored to {data.client.fitness_level.toLowerCase()} level</p></div></div>{plan.workouts.map((w,wi)=><article className="workout-card" key={w.id}><button className="workout-summary" onClick={()=>setOpen(open===wi?-1:wi)}><span className="day-box"><b>{w.day.slice(0,3)}</b><small>{w.focus}</small></span><span><strong>{w.title}</strong><small><Clock3 size={14}/>{w.duration} min · {w.exercises.length} exercises</small></span><i className={`status ${wi<2?'completed':'upcoming'}`}>{wi<2?'Progressed':'Maintained'}</i><ChevronDown className={open===wi?'rotate':''}/></button>{open===wi&&<div className="exercise-table"><div className="exercise-head"><span>Exercise</span><span>Sets</span><span>Reps</span><span>Weight / intensity</span><span>Rest</span></div>{w.exercises.map((e,ei)=><div className="exercise-row" key={ei}><label><b>{ei+1}</b><input aria-label="Exercise name" value={e.name} onChange={x=>editExercise(wi,ei,'name',x.target.value)}/><small>{e.instructions}</small></label><input aria-label="Sets" type="number" value={e.sets} onChange={x=>editExercise(wi,ei,'sets',Number(x.target.value))}/><input aria-label="Repetitions" value={e.reps} onChange={x=>editExercise(wi,ei,'reps',x.target.value)}/><input aria-label="Weight or intensity" value={e.intensity} onChange={x=>editExercise(wi,ei,'intensity',x.target.value)}/><input aria-label="Rest period" value={e.rest} onChange={x=>editExercise(wi,ei,'rest',x.target.value)}/></div>)}</div>}</article>)}</section>{saved&&<div className="toast"><Check size={17}/>Plan saved</div>}</div>{sendOpen&&<SendPlanModal clientName={data.client.name} onClose={()=>setSendOpen(false)} onSend={publish}/>}</Shell>
}

function SendPlanModal({clientName,count,onClose,onSend}:{clientName?:string;count?:number;onClose:()=>void;onSend:(values:{channel:string;available_at:string})=>Promise<void>}) { const [channel,setChannel]=useState('in_app'); const [available,setAvailable]=useState(''); const [sending,setSending]=useState(false); const label=clientName||`${count} clients`; async function submit(e:FormEvent){e.preventDefault();setSending(true);await onSend({channel,available_at:available?new Date(available).toISOString():new Date().toISOString()});setSending(false)} return <div className="modal-backdrop"><form className="modal compact" onSubmit={submit}><div className="modal-title"><div><span>Plan delivery</span><h2>Publish to {label}</h2></div><button type="button" aria-label="Close" onClick={onClose}><X/></button></div><div className="delivery-options"><label className={channel==='in_app'?'selected':''}><input type="radio" name="channel" value="in_app" checked={channel==='in_app'} onChange={e=>setChannel(e.target.value)}/><span><strong>In-app notification</strong><small>Publishes the plan directly in the client workspace.</small></span></label><label className={channel==='email_and_in_app'?'selected':''}><input type="radio" name="channel" value="email_and_in_app" checked={channel==='email_and_in_app'} onChange={e=>setChannel(e.target.value)}/><span><strong>Email and in-app</strong><small>In-app publishing works now. Email sends when an email service is connected.</small></span></label></div><Field label="Make available"><input autoFocus type="datetime-local" value={available} onChange={e=>setAvailable(e.target.value)}/></Field><p className="delivery-note">Leave the date empty to publish immediately. Clients can view the week, confirm their schedule, and leave feedback.</p><div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={sending}>{available?'Schedule plan':'Publish now'} <ChevronRight size={16}/></button></div></form></div> }

function LogWorkout({session,onClose,onSaved}:{session:Session;onClose:()=>void;onSaved:()=>void}) { const [duration,setDuration]=useState(String(session.duration||'')); const [difficulty,setDifficulty]=useState(String(session.difficulty||6)); const [notes,setNotes]=useState(session.notes||''); async function submit(e:FormEvent){e.preventDefault();await fetch(apiUrl(`sessions/${session.id}`),{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:'completed',duration:Number(duration),difficulty:Number(difficulty),notes})});onSaved()} return <div className="modal-backdrop"><form className="modal compact" onSubmit={submit}><div className="modal-title"><div><span>Workout log</span><h2>{session.title}</h2></div><button type="button" aria-label="Close" onClick={onClose}><X/></button></div><div className="form-grid"><Field label="Duration (minutes)"><input autoFocus required type="number" value={duration} onChange={e=>setDuration(e.target.value)}/></Field><Field label="Difficulty (1–10)"><input required min="1" max="10" type="number" value={difficulty} onChange={e=>setDifficulty(e.target.value)}/></Field><Field label="Completed work" wide><textarea defaultValue={session.performance.map(p=>`${p.exercise}: ${p.sets} at ${p.load}`).join('\n')} placeholder="Sets, reps, and weight used"/></Field><Field label="Client notes" wide><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="How did the session feel?"/></Field></div><div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary">Save workout</button></div></form></div> }

function ProgressModal({clientId,onClose,onSaved}:{clientId:number;onClose:()=>void;onSaved:()=>void}) { const [data,setData]=useState<Record<string,string>>({}); async function submit(e:FormEvent){e.preventDefault();await fetch(apiUrl(`clients/${clientId}/progress`),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});onSaved()} return <div className="modal-backdrop"><form className="modal compact" onSubmit={submit}><div className="modal-title"><div><span>Progress check-in</span><h2>Record new measurements</h2></div><button type="button" onClick={onClose} aria-label="Close"><X/></button></div><div className="form-grid">{[['weight','Weight (kg)'],['waist','Waist (cm)'],['body_fat','Body fat (%)'],['squat_max','Squat best (kg)']].map(([k,l],i)=><Field label={l} key={k}><input autoFocus={i===0} type="number" step=".1" value={data[k]||''} onChange={e=>setData(d=>({...d,[k]:e.target.value}))}/></Field>)}<Field label="Client feedback" wide><textarea value={data.feedback||''} onChange={e=>setData(d=>({...d,feedback:e.target.value}))} placeholder="Recovery, comfort, energy, confidence…"/></Field><Field label="Progress photo" wide><input className="file-input" type="file" accept="image/*"/></Field></div><div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary">Save check-in</button></div></form></div> }

export default function App(){useInterfaceTranslation();return <Routes><Route path="/login" element={<Login/>}/><Route path="/client" element={<AuthGate role="client"><ClientWorkspace/></AuthGate>}/><Route path="/client/:clientId" element={<AuthGate role="trainer"><ClientView/></AuthGate>}/><Route path="/clients/:clientId/preview" element={<AuthGate role="trainer"><ClientView/></AuthGate>}/><Route path="/" element={<AuthGate role="trainer"><Dashboard/></AuthGate>}/><Route path="/clients" element={<AuthGate role="trainer"><ClientDirectory/></AuthGate>}/><Route path="/schedule" element={<AuthGate role="trainer"><SchedulePage/></AuthGate>}/><Route path="/reports" element={<AuthGate role="trainer"><ReportsPage/></AuthGate>}/><Route path="/profile" element={<AuthGate role="trainer"><TrainerProfile/></AuthGate>}/><Route path="/clients/:clientId" element={<AuthGate role="trainer"><ClientPage/></AuthGate>}/><Route path="/clients/:clientId/plan" element={<AuthGate role="trainer"><ClientPage planOnly/></AuthGate>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes>}
